// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using CSDL7.MasterService.Services.Departments;
using CSDL7.MasterService.Services.Dtos.Departments;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace CSDL7.MasterService.Services.Departments;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDepartmentsAppService), typeof(DepartmentsClientProxy))]
public partial class DepartmentsClientProxy : ClientProxyBase<IDepartmentsAppService>, IDepartmentsAppService
{
    public virtual async Task<PagedResultDto<DepartmentDto>> GetListAsync(GetDepartmentsInput input)
    {
        return await RequestAsync<PagedResultDto<DepartmentDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetDepartmentsInput), input }
        });
    }

    public virtual async Task<DepartmentDto> GetAsync(Guid id)
    {
        return await RequestAsync<DepartmentDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<DepartmentDto> CreateAsync(CreateDepartmentDto input)
    {
        return await RequestAsync<DepartmentDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateDepartmentDto), input }
        });
    }

    public virtual async Task<DepartmentDto> UpdateAsync(Guid id, UpdateDepartmentDto input)
    {
        return await RequestAsync<DepartmentDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateDepartmentDto), input }
        });
    }

    public virtual async Task CallPingEmailAsync()
    {
        await RequestAsync(nameof(CallPingEmailAsync));
    }
}
