// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using CSDL7.MasterService.Services.Districts;
using CSDL7.MasterService.Services.Dtos.Districts;
using CSDL7.MasterService.Services.Dtos.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace CSDL7.MasterService.Services.Districts;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDistrictsAppService), typeof(DistrictsClientProxy))]
public partial class DistrictsClientProxy : ClientProxyBase<IDistrictsAppService>, IDistrictsAppService
{
    public virtual async Task<PagedResultDto<DistrictWithNavigationPropertiesDto>> GetListAsync(GetDistrictsInput input)
    {
        return await RequestAsync<PagedResultDto<DistrictWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetDistrictsInput), input }
        });
    }

    public virtual async Task<DistrictWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<DistrictWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<DistrictDto> GetAsync(Guid id)
    {
        return await RequestAsync<DistrictDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetProvinceLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetProvinceLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<DistrictDto> CreateAsync(DistrictCreateDto input)
    {
        return await RequestAsync<DistrictDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DistrictCreateDto), input }
        });
    }

    public virtual async Task<DistrictDto> UpdateAsync(Guid id, DistrictUpdateDto input)
    {
        return await RequestAsync<DistrictDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(DistrictUpdateDto), input }
        });
    }
}
