// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using CSDL7.MasterService.Services.Dtos.Provinces;
using CSDL7.MasterService.Services.Provinces;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace CSDL7.MasterService.Services.Provinces;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProvincesAppService), typeof(ProvincesClientProxy))]
public partial class ProvincesClientProxy : ClientProxyBase<IProvincesAppService>, IProvincesAppService
{
    public virtual async Task<PagedResultDto<ProvinceDto>> GetListAsync(GetProvincesInput input)
    {
        return await RequestAsync<PagedResultDto<ProvinceDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetProvincesInput), input }
        });
    }

    public virtual async Task<ProvinceDto> GetAsync(Guid id)
    {
        return await RequestAsync<ProvinceDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ProvinceDto> CreateAsync(ProvinceCreateDto input)
    {
        return await RequestAsync<ProvinceDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ProvinceCreateDto), input }
        });
    }

    public virtual async Task<ProvinceDto> UpdateAsync(Guid id, ProvinceUpdateDto input)
    {
        return await RequestAsync<ProvinceDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ProvinceUpdateDto), input }
        });
    }
}
