// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using CSDL7.MasterService.Services.Dtos.Shared;
using CSDL7.MasterService.Services.Dtos.Wards;
using CSDL7.MasterService.Services.Wards;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace CSDL7.MasterService.Services.Wards;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWardsAppService), typeof(WardsClientProxy))]
public partial class WardsClientProxy : ClientProxyBase<IWardsAppService>, IWardsAppService
{
    public virtual async Task<PagedResultDto<WardWithNavigationPropertiesDto>> GetListAsync(GetWardsInput input)
    {
        return await RequestAsync<PagedResultDto<WardWithNavigationPropertiesDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetWardsInput), input }
        });
    }

    public virtual async Task<WardWithNavigationPropertiesDto> GetWithNavigationPropertiesAsync(Guid id)
    {
        return await RequestAsync<WardWithNavigationPropertiesDto>(nameof(GetWithNavigationPropertiesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WardDto> GetAsync(Guid id)
    {
        return await RequestAsync<WardDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<LookupDto<Guid>>> GetDistrictLookupAsync(LookupRequestDto input)
    {
        return await RequestAsync<PagedResultDto<LookupDto<Guid>>>(nameof(GetDistrictLookupAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LookupRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<WardDto> CreateAsync(WardCreateDto input)
    {
        return await RequestAsync<WardDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WardCreateDto), input }
        });
    }

    public virtual async Task<WardDto> UpdateAsync(Guid id, WardUpdateDto input)
    {
        return await RequestAsync<WardDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(WardUpdateDto), input }
        });
    }
}
